// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjrhsjrijhjnyyglxgfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqcmhzanJpamhqbnl5Z2x4Z2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTg0ODYsImV4cCI6MjA2MDEzNDQ4Nn0.D6NwXkTLcB0G9bPjFkjqaUpfB8066-18QoPSqk7iLes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);